version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: day_scheduler_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: day_scheduler
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - day_scheduler_network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: day_scheduler_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - day_scheduler_network

  day-scheduler-app:
    build: .
    container_name: day_scheduler_app
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: day_scheduler
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - day_scheduler_network

volumes:
  mongodb_data:

networks:
  day_scheduler_network:
    driver: bridge 